config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :profile, only: [:index]

  resources :ious, only: [:new, :create, :destroy, :update, :edit] do
    resources :charges
  end

  root to: "profile#index"

end

app/models/iou.rb
class Iou < ActiveRecord::Base

  validates :title, :amount, :name, :contact, :user_id, presence: true
  validates :amount, numericality: {greater_than: 0}
  validates_format_of :contact,:with => Devise::email_regexp

  belongs_to :user

  def get_colour
    if self.status == "created"
      "red lighten-2"
    elsif self.status == "pending"
      "purple lighten-2"
    elsif self.status == "paid"
      "blue-grey lighten-4"
    end
  end

  def send_and_reschedule(mailer = IouMailer)
    unless self.status == 'paid'
      mailer.send_spam(self)
      self.delay(run_at: Time.new + 10).send_and_reschedule(mailer)
    end
  end

  def update_status
    self.status == 'pending' ? self.status = 'paid' : self.status = 'pending'
    self.save
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :ious

  validates :username, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
    
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @iou = Iou.find(params[:iou_id])
  end

  def create
    @iou = Iou.find(params[:iou_id])
    @amount = (@iou.amount*100).to_i

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'gbp'
    )

    @iou.update_status

    rescue Stripe::CardError => e

    flash[:error] = e.message
    redirect_to new_iou_charge_path(@iou)
  end


end

app/controllers/ious_controller.rb
class IousController < ApplicationController

  before_action :authenticate_user!, except: [:edit, :update]

  def new
    @iou = Iou.new
  end

  def create
    @iou = Iou.create(iou_params)
    if @iou.save
      IouMailer.initial_email(@iou).deliver_now
      redirect_to '/'
    else
      flash[:notice] = @iou.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit
    @iou = Iou.find(params[:id])
  end

  def update
    @iou = Iou.find(params[:id])
    @iou.update_status
    @iou.send_and_reschedule
    redirect_to '/'
  end

  def destroy
    @iou = Iou.find(params[:id])
    @iou.destroy
    flash[:notice] = 'Iou deleted'
    redirect_to '/'
  end

private

  def iou_params
    iou_user = {user: current_user}
    params.require(:iou).permit(:title,:amount,:name,:contact).merge(iou_user)
  end

end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController

  before_action :authenticate_user!

  def index
    if current_user
      @ious = current_user.ious.order(created_at: :desc)
    end
  end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/ious_helper.rb
module IousHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/charges/create.html.erb
<div class="center">
  <label class="amount">
    <h4>Thanks, you paid <b><%="£%.2f" % @iou.amount%></b></h4>
  </label>
</div>

app/views/charges/new.html.erb
<div class="center">
  <%= form_tag iou_charges_path(@iou) do %>
  <article>
    <% if flash[:error].present? %>
    <div id="error_explanation">
      <p><%= flash[:error] %></p>
    </div>
    <% end %>
    <label class="amount">
      <h5>Amount: <%= "£%.2f" % @iou.amount %></h5>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
  data-description="Pay IOU"
  data-currency="gbp"
  data-amount="<%= @iou.amount*100.to_i %>"
  data-locale="auto"
  data-email="<%= @iou.contact%>"></script>

  <% end %>
</div>

app/views/ious/edit.html.erb
<div class="center">
  <%= form_for @iou do |f| %>
    <%= f.submit class: "waves-effect relative btn blue-grey ligthen-3"%>
  <% end %>
</div>

app/views/ious/new.html.erb
<div class="container" id="form-box">
  <div class="col s12 l12">
    <%= form_for @iou do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>
      <%= f.label :amount %>
      <%= f.text_field :amount, placeholder: "£" %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :contact %>
      <%= f.email_field :contact %>
      <p><%= f.submit class: "waves-effect relative btn blue-grey ligthen-3" %></p>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Uoi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>

  <div class="navbar-fixed blue-grey ligthen-3">
    <nav class="blue-grey ligthen-3">
      <div class="nav-wrapper blue-grey ligthen-3">
        <a href="/" class="brand-logo center blue-grey ligthen-3" style="height:55px;margin-top:5px"><img src="/logo_small.png" style="height:55px;" /></a>

        <% if current_user %>
          <span id="username">
            Signed in as : <b><%= current_user.username %></b>
          </span>

          <ul class="right">
            <li>
              <%= link_to "Log out", destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        <% else %>
          <ul class="right">
            <li>
              <%= link_to "Log in", new_user_session_path %>
              <%= link_to "Sign up", new_user_registration_path %>
            </li>
          </ul>
        <% end %>
      </div>
    </nav>
  </div>

  <div class="container" id="site-body">
    <% if notice || alert %>
      <div class="row ">
        <div class="col s6 offset-s3 m6 offset-m3">
          <div class="card-panel small" id="flash">
            <p class="notice center-align"><%= notice %></p>
            <p class="alert center-align"><%= alert %></p>
          </div>
        </div>
      </div>
    <% end %>

    <%= yield %>

  </div>


</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Uoi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>

  <div class="navbar-fixed blue-grey ligthen-3">
    <nav class="blue-grey ligthen-3">
      <div class="nav-wrapper blue-grey ligthen-3">
        <a href="/" class="brand-logo center blue-grey ligthen-3" style="height:55px;margin-top:5px"><img src="/logo_small.png" style="height:55px;" /></a>

        <% if current_user %>
          <span id="username">
            Signed in as : <b><%= current_user.username %></b>
          </span>

          <ul class="right">
            <li>
              <%= link_to "Log out", destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        <% else %>
          <ul class="right">
            <li>
              <%= link_to "Log in", new_user_session_path %>
              <%= link_to "Sign up", new_user_registration_path %>
            </li>
          </ul>
        <% end %>
      </div>
    </nav>
  </div>

  <div class="container" id="site-body">
    <% if notice || alert %>
      <div class="row ">
        <div class="col s6 offset-s3 m6 offset-m3">
          <div class="card-panel small" id="flash">
            <p class="notice center-align"><%= notice %></p>
            <p class="alert center-align"><%= alert %></p>
          </div>
        </div>
      </div>
    <% end %>

    <%= yield %>

  </div>


</body>
</html>

app/views/users/_uoi_button.html.erb
<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
  <a class="btn-floating btn-large red">
    <i class="large material-icons">receipt</i>
  </a>
</div>